.github/actions/setup-environment/action.yml, .github/workflows/add-team-label.yml, .github/workflows/build-lint-test.yml, .github/workflows/main.yml, .yarnrc.yml
Instead of copy-pasting the implementation of add-team-label to other repositories, such as metamask-extension and metamask-mobile, it should be possible to call the workflow directly from the github-tools repository, if we make it a reusable workflow. This is great, because if we make a change to the workflow in the github-tools repository, the changes propagate to other repositories as well.
More information about reusable workflows: https://docs.github.com/en/actions/using-workflows/reusing-workflows
This kind of aligns with https://github.com/MetaMask/metamask-extension/issues/25509, but not exactly. The shared library would still be needed nevertheless, as this is only sharing the workflow definition, but not the scripts that are run during the workflow. The scripts still need to …
=> feat: add team label reusable workflow

.github/workflows/lint-workflows.yml, .github/workflows/main.yml
This PR introduces a reusable workflow to lint workflows across repositories. 
Contributes to: https://github.com/MetaMask/metamask-extension/issues/28572
=> feat: lint-workflows

.github/actions/setup-environment/action.yml, .github/workflows/lint-workflows.yml
The previous PR made two changes, both of which are no longer needed, at least for the moment:
**Not using containers at the moment**
Using `ubuntu-22.04` with no container instead
```
- run: ${{ job.container && 'sudo' || '' }} corepack enable
```
**Not using self-hosted runners at the moment**
GitHub-hosted runners seem sufficient
```
run: ${{ steps.download-actionlint.outputs.executable }} -color -ignore 'label ".+" is unknown'
```
=> revert: Enable benchmarks in metamask-extension (#38)

.github/workflows/test-checkout-and-setup.yml
Finalize `test-do-not-checkout-twice` now that we have the SHA
=> ci: followup to checkout-and-setup with new SHA

.github/workflows/add-item-to-project.yml
Teams like the Wallet Framework team have a ton of repos under our care and for this reason we need to be able to auto add issues/PRs to our project board across all those repos. The github projects built in workflow only allows for up to 20 workflows which isn't enough to cover all the repos we have so we are creating a shared workflow that we can use across many repos in order to do the above. 
Any team can use this workflow by passing the project url and team name information.
=> feat(projects): Add issues and PRs to github projects by team

.github/workflows/add-item-to-project.yml
I mistakenly thought I had to include the github token in the secrets that the workflow accepts. It gets it automatically. Additionally having the secrets input defined as expecting GH Token causes an issue because GH Token is reserved
=> fix(actions): Remove GH Token from secrets it gets it automatically

.github/workflows/add-item-to-project.yml
This PR fixes an issue with the reusable workflow for adding issues and PRs to project boards. The workflow was attempting to use a GitHub token passed from calling workflows, but didn't properly define the secrets input in the `workflow_call` section.
- Added a `secrets` section to the `workflow_call` definition
- Properly defined the `github-token` secret with description and required flag
- Ensured consistent naming between the defined secret and its usage in the action
=> fix: add proper secrets definition to `add item to project`  workflow

.github/workflows/changelog-check.yml, package.json, src/changelog-check.ts, src/scripts/count-references-to-contributor-docs/cli.ts, yarn.lock
This PR introduces a new CI workflow that enforces the inclusion of a CHANGELOG entry for any changes made by developers. It supports both single-package repositories and monorepos.
Usage examples:
Extension: https://github.com/MetaMask/metamask-extension/pull/31706
Core (Monorepo): https://github.com/MetaMask/core/pull/5575
Fixes: https://github.com/MetaMask/MetaMask-planning/issues/3678
=> feat: GH action to remind developers to add release notes in CHANGELOG.md 

.github/workflows/changelog-check.yml, src/changelog-check.ts
This PR improves the changelog check workflow in two ways:
1. **Skip package.json version-only changes**: The changelog check will now skip package.json files that only contain version changes, reducing unnecessary changelog requirements for simple version bumps.
2. **Fix workflow reference**: Changed the workflow checkout to use the same commit SHA that's referenced in the workflow call instead of `main`, preventing potential issues from breaking changes in the main branch.
1. Using [Core](https://github.com/MetaMask/core) monorepo:
```bash
git checkout release/372.0.0
copy https://github.com/MetaMask/github-tools/blob/main/src/changelog-check.ts file to scripts folder
yarn changelog:check . main 5690
copy https://github.com/MetaMask/github-tools/blob/ce4ba9de297920ebcfacb2465e6f552baf255 …
```
=> feat: improve changelog check workflow

.github/workflows/changelog-check.yml
This PR fixes the workflow checkout reference issue in the changelog check workflow. Previously, the workflow was using `${{ github.sha }}`([here](https://github.com/MetaMask/core/actions/runs/14605760515/job/40974318922?pr=5693)) which caused a "not our ref" error because it was trying to use the current workflow run's SHA instead of the reference used to call the workflow.
- Updated workflow checkout to use `${{ github.action_ref }}` to match the reference used in the workflow call
- This ensures the workflow uses the same reference (SHA or branch) that was specified in the workflow call
=> fix(changelog-check): use correct reference in workflow checkout

.github/workflows/changelog-check.yml
This PR adds an `action-sha` input to the changelog check workflow to ensure we're using the correct version of the github-tools repository. This is necessary because:
1. When a workflow is called using a specific SHA (e.g., `@91e349d177db2c569e03c7aa69d2acb404b62f75`), we need to use that exact same SHA when checking out the repository
2. Previous attempts using `github.action_ref`, `github.sha`, or other GitHub context variables didn't work because:
- `github.action_ref` includes the full ref path (e.g., `+refs/heads/v4*:refs/remotes/origin/v4*`)
- `github.sha` refers to the current workflow run's SHA
- Other context variables don't reliably provide the correct SHA
This is a short-term fix. In the future, we plan to:
1. Move the workflow to a separate repository
2. Implement proper …
=> chore(changelog-check): add action-sha input for correct repository checkout

src/changelog-check.ts
This PR adds support for excluding private packages from the changelog check workflow. Private packages in a monorepo typically don't require public changelog entries since they are not published to npm.
- Added `isPrivatePackage` function to detect private packages by checking the `private` field in package.json
- Added caching for private package checks to optimize performance when multiple files in the same package are changed
- Modified `getChangedPackages` to skip private packages regardless of which files were changed
- Added logging when private packages are skipped for better visibility
1. Using [Core](https://github.com/MetaMask/core) monorepo:
- First, make the `phishing-controller` package private by adding `"private": true` to its package.json
- Make dummy changes to …
=> chore(changelog-check): exclude private packages from changelog check

.github/workflows/post-gh-rca.yml
- Adds a prefix for wildcard labels that start with `team-` or `regression-`
- TODO in this ticket: add those labels to the form so they get auto filled
=> feat(INFRA-2510): add team and regression labels

.github/workflows/stale-issue-pr.yml
This PR fix the config from https://github.com/MetaMask/github-tools/pull/41
**PRs**
-  stale after 90 days. 7 days more before closing.
**Issues**
- stale after 30 days. 60 days more before closing.
=> chore: adapt common stale bot config

.github/workflows/stale-issue-pr.yml
update stale bot to process only issues with needs-information, needs-reproduction label
=> chore: update stale bot to process only issues with needs-information, needs-reproduction label

.github/scripts/stable-sync.js, .github/workflows/stable-sync.yml
This PR is intended to add as functionality a workflow call that will:
- Create a `stable-main-{release}` branch
- Run the script that will ensure the branch will from a known good state and will take specific files from the stable branch
- Create a PR against `main`
Examples made on a forked metamask-mobile repo:
https://github.com/MetaMask/experimental-metamask-mobile-dso-tests/actions/runs/15068855926
This file (`stable-sync.js`) is a script that synchronizes changes between the `main` and `stable` branches. Here's a breakdown of what it does:
**Branch Management:**
- Takes a branch name as an argument (defaults to 'stable-main' if not provided)
- Checks if the branch exists
- If it exists, checks it out
- If it doesn't exist, creates a new branch
**Synchronization Process:**
- Fetches …
=> feat(gh-action): create workflow for automatize stable-main creation

.github/scripts/generate-rc-commits.mjs
=> additional logging on generation of commits.csv

.github/workflows/upload-yarn-binary.yml
**What is the current state of things and why does it need to change?**
Currently, there is no automated way to upload Yarn binaries to GitHub Releases in this repository. This is needed to provide a reliable, rate-limit-free, and cost-effective way for CI pipelines and other consumers to fetch specific Yarn versions.
**What is the solution your changes offer and how does it work?**
This PR introduces a new GitHub Actions workflow (`.github/workflows/upload-yarn-binary.yml`) that allows maintainers to manually upload a specific Yarn version (e.g., 4.9.1) as a release asset. The workflow:
- Accepts a Yarn version as input.
- Downloads the corresponding `yarn.js` binary.
- Creates or updates a GitHub Release for that version.
- Uploads the binary as a release asset.
- Outputs the download …
=> feat: add workflow to upload Yarn binary to GitHub Release

.github/scripts/create-platform-release-pr.sh
On Extension, the release branches are named `Version-vx.x.x`, not `release/x.x.x`
=> fix: "Create Release Pull Request" on Extension

.github/scripts/stable-sync.js, .github/workflows/stable-sync.yml
This PR consolidates duplicate script functionality from the Mobile and Extension repositories into our centralized GitHub tools repository. Instead of maintaining separate copies of similar scripts in each platform repository, both teams now reference a single, shared implementation via reusable workflows.
- Eliminates code duplication between Mobile and Extension platforms
- Provides a single source of truth for shared script logic
- Reduces maintenance overhead while maintaining existing functionality
- Follows our established pattern of centralizing common tooling
This change preserves all current processes and workflows while creating a more maintainable foundation for future updates.
See: https://github.com/MetaMask/MetaMask-planning/issues/4210
=> feat(stable-sync): Move stable sync process within github tools

.github/workflows/pr-line-check.yml
Adapt `PR size job` to add sizes label:
```
default values
size-XS: ≤ 10 lines
size-S: ≤ 100 lines
size-M: ≤ 500 lines
size-L: ≤ 1000 lines
size-XL: > 1000 lines
```
Also adapt the calculation of changes by adding +0 in the awk END block to ensure that when there are no changes, awk outputs 0 instead of an empty string:
```
{print add} → {print add+0}
{print del} → {print del+0}
```
tested here: https://github.com/MetaMask/metamask-mobile/actions/runs/16826192546/job/47663091866
=> ci: adapt PR size job to add sizes label

.github/scripts/create-platform-release-pr.sh, .github/scripts/generate-rc-commits.mjs, .github/workflows/create-release-pr.yml
Ticket: https://consensyssoftware.atlassian.net/browse/INFRA-2867
The Github Action is supposed to accept 3 kind of references as inputs: branch name, tag, commit hash. However, it doesn’t work with branch names. To fix this, we should check the format of the references passed to [filterCommitsByTeam](https://github.com/MetaMask/github-tools/blob/dde6d530bebae07d1e50180894ab2cac64170a2c/.github/scripts/generate-rc-commits.mjs#L62) function in github-tools repo, detect if the reference is a branch name, and if so, prefix it with origin/. Otherwise the Github Action can’t find the branch. Additionally we should check if the branch exists before calling [filterCommitsByTeam](https://github.com/MetaMask/github-tools/blob/dde6d530bebae07d1e50180894ab2cac64170a2c/.github/scripts/generate-rc-comm …
=> INFRA-2867-Fix workflow inputs to allow branch name

.github/scripts/create-platform-release-pr.sh
Ticket: https://consensyssoftware.atlassian.net/browse/INFRA-2867
Skip version bump PR creation if already exists, commit in main
```
The Github Action is not idempotent. We should be able to re-launch the Github Action several times successfully.
- If the version bump PR already exists, Github Action will fail (example [here](https://github.com/MetaMask/metamask-extension/actions/runs/16743685688/job/47397153780)). It needs to be deleted first before re-running the Github Action.
```
Error reproduced [here](https://github.com/consensys-test/metamask-extension-test-workflow2/actions/runs/17273008509/job/49022525460)
Fix tested here: https://github.com/consensys-test/metamask-extension-test-workflow2/actions/runs/17276145574/job/49033208400
=> INFRA-2867: Skip version bump PR creation if already exists, commit in main

.github/scripts/get-release-timelines.sh, .github/workflows/stable-sync.yml
The purpose of this PR is to remove all references to `master` branch right after we've renamed `master` branch into `stable` on metamask-extension repo.
=> chore(master): rename master branch into stable

.github/scripts/create-flaky-test-report.mjs, .github/scripts/post-merge-validation-tracker.mjs
=> ci: small fixes

.github/scripts/create-platform-release-pr.sh, .github/scripts/tests/test-create-platform-release-pr-full.sh, .github/scripts/tests/test-create-platform-release-pr-functions.sh
The purpose of this PR is to rename release branches from `Version-vx.y.z` format into `release/x.y.z`, in order to align with metamtask-mobile repo format.
=> chore(branches): rename Version-vx.y.z branches into release/x.y.z
